# -*- coding: utf-8 -*-
"""Guia segmentación .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b7K9MEZpxtt1JTzrrlAYidStsxqz5Pi9

#Importaciones
"""

'''
Librerias
Separo por categorias
'''

'''
Primero manejo de imagenes y algebra lineal
'''
import cv2
import numpy as np

'''
Segmentación, filtros y morfologia
'''
from skimage.filters import threshold_otsu, gaussian
from skimage.segmentation import active_contour, watershed
from skimage.morphology import erosion, dilation, opening, closing, skeletonize, disk
from skimage.draw import polygon
from skimage.color import rgb2gray
from scipy import ndimage
from skimage.feature import peak_local_max

'''
Visualizacion
'''
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

"""##Configuración global

Separo la configuracion del codigo, logrando aca cambiar la imagen o kernel, estando en un solo lugar
"""

#Ruta de la Imagen en drive
IMG_PATH= '/content/drive/MyDrive/PSIB/Imagenes/Guia segmentación PSIB /1019.jpg'

#Parametros de morfologia
MORPH_RADIUS=5 #radio del elemento estructurante

#Parametros de K-means
K_CLUSTERS=3 #numero de clusters
''' Antes:
#Parametros del snake
SNAKE_ALPHA  = 0.015      # rigidez de la curva
SNAKE_BETA   = 10         # suavidad de la curva
SNAKE_GAMMA  = 0.001      # tamaño de paso
SNAKE_ITERS  = 2500       # iteraciones máximas
'''
SNAKE_ALPHA  = 0.1    # era 0.015 → más rígido, evita que colapse
SNAKE_BETA   = 1.0    # era 10    → menos suave, el borde se adapta mejor
SNAKE_GAMMA  = 0.01   # era 0.001 → paso más grande, converge más rápido
SNAKE_ITERS  = 2500   # igual

# Estilo general de los plots
plt.rcParams['figure.dpi'] = 110
plt.rcParams['axes.titlesize'] = 11

"""##Carga y procesamiento

Convierto en escala de grises y suavizado gaussiano para reducir ruido antes de segmentar. Esto por que la piel tiene texturas finas
"""

#Carga imagen
img_bgr = cv2.imread(IMG_PATH)
if img_bgr is None:
    raise FileNotFoundError(f'No se encontro la imagen en {IMG_PATH}')

#openCV carga en bgr --> convierto a rgb para que matplot muestre bien colores
img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

#Preprocesamiento
#escala de grises: varios metodos de segmentación: trabaja sobre 1 canal
gray = cv2.cvtColor(img_bgr , cv2.COLOR_BGR2GRAY)

'''
Suavizado gaussiano: reduce el ruido de alta frecuencia
sigma=2 es un valor conservador; si hay mucho ruido , deberia aumentarlo
'''
gray_smooth = gaussian(gray, sigma=2)

#visualizacion del estado incial
fig, axes = plt.subplots(1, 3, figsize=(12, 4))
axes[0].imshow(img_rgb);          axes[0].set_title("Original (RGB)");        axes[0].axis('off')
axes[1].imshow(gray, cmap='gray'); axes[1].set_title("Escala de grises");      axes[1].axis('off')
axes[2].imshow(gray_smooth, cmap='gray'); axes[2].set_title("Suavizado gaussiano"); axes[2].axis('off')
plt.suptitle("Preprocesamiento", fontweight='bold')
plt.tight_layout()
plt.show()

print(f"Tamaño de imagen: {img_rgb.shape}")

"""#Metodo de Otsu

busca automáticamente el umbral que maximiza la varianza entre dos grupos de píxeles (los claros = piel sana, los oscuros = lesión). Es rápido y no requiere parámetros manuales.

Limitación: Asume que la imagen tiene exactamente dos regiones bien separadas en intensidad. Si la lesión tiene colores heterogéneos (como melanomas avanzados), no funciona bien.
"""

#threshold_otsu devuelve el valor umbral optimo ( un numero, no la mascara)
umbral_otsu= threshold_otsu(gray)

#Creo la mascara binaria: true donde el pixel es + oscuro que el umbral
#(la lesion es oscura sobre fondo claro)
mascara_otsu = gray <umbral_otsu

#visualizacion
fig, axes = plt.subplots(1, 3, figsize=(13, 4))

axes[0].imshow(img_rgb)
axes[0].set_title("Original")
axes[0].axis('off')

# Histograma con el umbral marcado
axes[1].hist(gray.ravel(), bins=256, color='gray', alpha=0.8)
axes[1].axvline(umbral_otsu, color='red', lw=2, label=f'Umbral = {umbral_otsu:.0f}')
axes[1].set_title("Histograma + umbral de Otsu")
axes[1].set_xlabel("Intensidad")
axes[1].set_ylabel("Cantidad de píxeles")
axes[1].legend()

axes[2].imshow(mascara_otsu, cmap='gray')
axes[2].set_title(f"Máscara Otsu (umbral={umbral_otsu:.0f})")
axes[2].axis('off')

plt.suptitle("Segmentación por Otsu", fontweight='bold')
plt.tight_layout()
plt.show()

"""#K-Means

agrupa los píxeles según su color RGB en K clusters. A diferencia de Otsu que usa solo intensidad, K-means usa la información de los 3 canales (rojo, verde, azul), lo que lo hace más robusto para lesiones pigmentadas con variaciones de color.

Limitación: No garantiza que el cluster más oscuro sea siempre la lesión. Hay que identificarlo manualmente o con algún criterio (acá usamos: el cluster cuya suma de canales RGB sea menor).
"""

#tengo que reformatear la imagen: de (alto, ancho,3) --> ( N_pixeles, 3)
#cv2.kmeans requiere float32
pixeles = img_rgb.reshape(-1,3).astype(np.float32)

#criterio de parada: cuando el error cambia menos de 0.2 o tras 100 iteraciones
criterio = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 100, 0.2)

#ejecuto k-means
#retorna: compacidad, etiquetas (que cluster es cada pixel), centros(color de cada cluster)
_, etiquetas, centros = cv2.kmeans(
    pixeles, K_CLUSTERS, None, criterio, 10, cv2.KMEANS_RANDOM_CENTERS
)

#reformateamos las etiquetas a la forma original de la imagen
mapa_clusters = etiquetas.reshape(img_rgb.shape[:2])
# Identificamos el cluster MÁS OSCURO (suma de RGB menor → más oscuro → lesión)
idx_oscuro = np.argmin(centros.sum(axis=1))
mascara_kmeans = (mapa_clusters == idx_oscuro)

# Imagen reconstruida coloreando cada píxel con el color de su cluster
img_kmeans_coloreada = centros[etiquetas.flatten()].reshape(img_rgb.shape).astype(np.uint8)

# Visualización
fig, axes = plt.subplots(1, 3, figsize=(13, 4))
axes[0].imshow(img_rgb);                  axes[0].set_title("Original");              axes[0].axis('off')
axes[1].imshow(img_kmeans_coloreada);     axes[1].set_title(f"K-means (K={K_CLUSTERS}) — clusters coloreados"); axes[1].axis('off')
axes[2].imshow(mascara_kmeans, cmap='gray'); axes[2].set_title("Máscara K-means (cluster oscuro)"); axes[2].axis('off')

plt.suptitle("Segmentación por K-means", fontweight='bold')
plt.tight_layout()
plt.show()

print("Centros de cada cluster (R, G, B):")
for i, c in enumerate(centros):
    marca = " ← lesión" if i == idx_oscuro else ""
    print(f"  Cluster {i}: R={c[0]:.0f}, G={c[1]:.0f}, B={c[2]:.0f}{marca}")

"""#Contornos activos

El snake es una curva que evoluciona desde una posición inicial (definida por el usuario) guiada por dos fuerzas:

Internas: mantienen la curva suave y continua (controladas por alpha y beta)
Externas: atraen la curva hacia bordes de la imagen (gradiente de intensidad)
La curva se inicializa como un círculo alrededor del centro de la imagen.

Limitación: Muy sensible a la posición inicial y a los parámetros. Si la lesión no está centrada o el borde no es claro, el snake puede no converger bien.
"""

# === CONTORNOS ACTIVOS (SNAKE) — versión mejorada ===

# --- Paso 1: encontrar el centro real de la lesión automáticamente ---
# En vez de asumir que la lesión está en el centro de la imagen,
# usamos Otsu para binarizar y luego calculamos el centroide del objeto más grande.
# Así el círculo inicial queda bien posicionado sin importar dónde esté la lesión.

_, binaria_ref = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
contornos_ref, _ = cv2.findContours(binaria_ref, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
contorno_mas_grande = max(contornos_ref, key=cv2.contourArea)

momentos = cv2.moments(contorno_mas_grande)
cx = int(momentos['m10'] / momentos['m00'])   # columna del centroide
cy = int(momentos['m01'] / momentos['m00'])   # fila del centroide

# Radio = 40% más grande que el radio equivalente del área detectada
# (el +40% asegura que el círculo inicial esté AFUERA de la lesión)
area_ref = cv2.contourArea(contorno_mas_grande)
radio = int(np.sqrt(area_ref / np.pi) * 1.4)

# --- Paso 2: construir el círculo inicial ---
gray_para_snake = gaussian(gray, sigma=3)
s = np.linspace(0, 2 * np.pi, 400)
contorno_inicial = np.array([
    cy + radio * np.sin(s),
    cx + radio * np.cos(s)
]).T

# --- Paso 3: ejecutar el snake ---
# Parámetros:
#   alpha → rigidez de la curva. Más alto = más rígido = menos riesgo de colapso
#   beta  → suavidad del contorno. Bajo = el contorno puede curvarse más (más detalle)
#   gamma → tamaño del paso de cada iteración. Más alto = converge más rápido
#   w_edge → peso de la atracción al borde (gradiente de intensidad). Es la fuerza principal
#   w_line → atracción a zonas oscuras/claras. 0 = no lo usamos (lo maneja w_edge)
snake = active_contour(
    gray_para_snake,
    contorno_inicial,
    alpha=SNAKE_ALPHA,    # en config: 0.1
    beta=SNAKE_BETA,      # en config: 1.0
    gamma=SNAKE_GAMMA,    # en config: 0.01
    w_line=0.0,
    w_edge=1.0,
    max_num_iter=SNAKE_ITERS
)

# --- Paso 4: convertir el contorno a máscara binaria ---
rr_poligono, cc_poligono = polygon(snake[:, 0], snake[:, 1], gray.shape)
mascara_snake = np.zeros(gray.shape, dtype=bool)
mascara_snake[rr_poligono, cc_poligono] = True

# Visualización
fig, axes = plt.subplots(1, 3, figsize=(13, 4))

axes[0].imshow(img_rgb)
axes[0].plot(contorno_inicial[:, 1], contorno_inicial[:, 0], '--r', lw=2, label='Inicio')
axes[0].plot(cx, cy, 'r+', ms=12, mew=2)   # marcamos el centroide
axes[0].set_title("Contorno inicial (centro automático)")
axes[0].legend()
axes[0].axis('off')

axes[1].imshow(img_rgb)
axes[1].plot(snake[:, 1], snake[:, 0], '-g', lw=2, label='Snake final')
axes[1].set_title("Contorno activo final")
axes[1].legend()
axes[1].axis('off')

axes[2].imshow(mascara_snake, cmap='gray')
axes[2].set_title("Máscara Snake")
axes[2].axis('off')

plt.suptitle("Segmentación por Contorno Activo (Snake)", fontweight='bold')
plt.tight_layout()
plt.show()

"""#Watershed

Imagina relevieve topografico donde las intensidades son alturas. Se inunda las cuencas desde marcadores ( semillas) y el agua se separa en las crestas, formando los bordes de segmentación.

Aca uso variante basada en transformacion de distancia
1.   Binarizamos con Otsu
2.   Calculamos la distancia de cada píxel al borde más cercano
3.   Los picos de esa distancia son los marcadores
4.   Watershed llena desde esos picos

tiene la limitacion de que puede sobresegmentar su hay muchos picos locales
"""

# Paso 1: suavizado + umbralización para obtener la región de la lesión
gray_suave = cv2.GaussianBlur(gray, (5, 5), 0)
_, binaria = cv2.threshold(gray_suave, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)

# Paso 2: transformada de distancia
# Cada píxel en True tendrá como valor su distancia al borde False más cercano
distancia = ndimage.distance_transform_edt(binaria)

# Paso 3: encontrar los picos locales (serán los marcadores/semillas)
coords_picos = peak_local_max(distancia, footprint=np.ones((3, 3)), labels=binaria)
mascara_picos = np.zeros(distancia.shape, dtype=bool)
mascara_picos[tuple(coords_picos.T)] = True
marcadores, _ = ndimage.label(mascara_picos)

# Paso 4: aplicar watershed
# Usamos -distancia porque watershed inunda desde los mínimos
etiquetas_ws = watershed(-distancia, marcadores, mask=binaria)

# La máscara final es cualquier píxel que pertenezca a algún segmento
mascara_watershed = etiquetas_ws > 0

# Visualización
fig, axes = plt.subplots(1, 4, figsize=(16, 4))
axes[0].imshow(img_rgb);                          axes[0].set_title("Original");          axes[0].axis('off')
axes[1].imshow(binaria, cmap='gray');             axes[1].set_title("Binaria (Otsu inv."); axes[1].axis('off')
axes[2].imshow(distancia, cmap='hot');            axes[2].set_title("Transformada dist."); axes[2].axis('off')
axes[3].imshow(mascara_watershed, cmap='gray');   axes[3].set_title("Máscara Watershed");  axes[3].axis('off')

plt.suptitle("Segmentación por Watershed", fontweight='bold')
plt.tight_layout()
plt.show()

"""#Morfologia Matematica"""

# Elemento estructurante: disco de radio MORPH_RADIUS
# El disco es isotrópico (igual en todas las direcciones), ideal para regiones circulares como lunares
elemento = disk(MORPH_RADIUS)

# Aplicamos cada operación sobre la máscara de Otsu
erosionada     = erosion(mascara_otsu, elemento)
dilatada       = dilation(mascara_otsu, elemento)
apertura       = opening(mascara_otsu, elemento)
cierre         = closing(mascara_otsu, elemento)
esqueleto      = skeletonize(mascara_otsu)

# Visualización de las 5 operaciones + la máscara original
fig, axes = plt.subplots(2, 3, figsize=(14, 9))

imagenes = [mascara_otsu, erosionada, dilatada, apertura, cierre, esqueleto]
titulos  = ["Original (Otsu)", "Erosión", "Dilatación", "Apertura", "Cierre", "Esqueletización"]

for ax, img_morf, titulo in zip(axes.ravel(), imagenes, titulos):
    ax.imshow(img_morf, cmap='gray')
    ax.set_title(titulo)
    ax.axis('off')

plt.suptitle(f"Morfología Matemática (elemento: disco, radio={MORPH_RADIUS})", fontweight='bold')
plt.tight_layout()
plt.show()

"""##Comparacion metodos"""

# === COMPARACIÓN FINAL ===

# Reunimos todas las máscaras en una lista con sus nombres
mascaras = [
    (img_rgb,           "Original"),
    (mascara_otsu,      "Otsu"),
    (mascara_kmeans,    "K-means"),
    (mascara_snake,     "Snake"),
    (mascara_watershed, "Watershed"),
    (apertura,          "Morfología\n(Apertura sobre Otsu)"),
]

fig, axes = plt.subplots(1, 6, figsize=(20, 4))

for ax, (imagen, titulo) in zip(axes, mascaras):
    if imagen.ndim == 3:
        ax.imshow(imagen)                    # imagen RGB
    else:
        ax.imshow(imagen, cmap='gray')       # máscara binaria
    ax.set_title(titulo, fontsize=10)
    ax.axis('off')

plt.suptitle("Comparación de métodos de segmentación", fontweight='bold', fontsize=13)
plt.tight_layout()
plt.show()

"""## Análisis comparativo

| Método | Ventajas | Limitaciones | Aplicación biomédica |
|--------|----------|--------------|----------------------|
| **Otsu** | Rápido, automático, sin parámetros | Solo funciona bien con 2 regiones bien separadas | Screening rápido, lesiones con contraste claro |
| **K-means** | Usa color (RGB), identifica múltiples regiones | Resultado varía según inicialización aleatoria | Análisis de heterogeneidad del color en melanomas |
| **Snake** | Contorno suave y continuo, flexible | Muy sensible a parámetros y posición inicial | Delineación precisa para medir área/perímetro |
| **Watershed** | Separa objetos que se tocan | Puede sobre-segmentar con muchos marcadores | Conteo de células/lesiones múltiples |
| **Morfología** | Refina otras máscaras, elimina ruido | No genera segmentación por sí sola | Post-procesamiento, extracción de forma y estructura |
"""