'''
EJECUTAR EN NOTEBOOK DE COLAB, DONDE LA RUTA DE IMAGEN SEA LA DE USTEDES, Y TENGAN TAMBIEN 
HECHO LA GUIA DE SEGMENTACION HECHA, SI NO LA TIENEN COPIEN LA QUE SUBI YO, ES LA QUE TIENE 
UN _.py
'''
"""Guia análisis de texturas y compresión.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ENOwyMoKQHujAKK-RpfWXKv9ZJgJRu-9

**Parte 1 — Análisis de texturas:**
- Preparación del ROI (cuantización, separación de canales)
- Descriptores morfométricos (área, perímetro, centroide)
- Descriptores de primer orden (media, desvío, entropía, skewness)
- Descriptores de segundo orden GLCM

**Parte 2 — Compresión:**
- Huffman
- RLE en dos direcciones
- JPEG con distintos factores de calidad
"""

#librerias de manejo de imagenes y algebra lineal
import cv2
import numpy as np
#segmentacion y morfologia
from skimage.filters import threshold_otsu, gaussian
from skimage.segmentation import active_contour, watershed
from skimage.morphology import erosion, dilation, opening, closing, skeletonize, disk
from skimage.draw import polygon
from skimage.color import rgb2gray
from scipy import ndimage
from skimage.feature import peak_local_max
#para texturas
from skimage.feature import graycomatrix, graycoprops   # GLCM
from skimage.measure import regionprops, label          # propiedades morfométricas
from scipy.stats import skew, entropy                   # estadísticas de primer orden
#compresion
import heapq                   # para Huffman (cola de prioridad)
from collections import Counter  # contar frecuencias de símbolos
import io                      # para JPEG en memoria
from PIL import Image          # para guardar/leer JPEG con distintas calidades
# Visualización
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
# Utilidades
import os
from google.colab import drive

#Ruta de la Imagen en drive
IMG_PATH= '/content/drive/MyDrive/PSIB/Imagenes/Guia segmentación PSIB /1019.jpg'

#parametros segmentacion
K_CLUSTERS=3 #numero de clusters
''' Antes:
#Parametros del snake
SNAKE_ALPHA  = 0.015      # rigidez de la curva
SNAKE_BETA   = 10         # suavidad de la curva
SNAKE_GAMMA  = 0.001      # tamaño de paso
SNAKE_ITERS  = 2500       # iteraciones máximas
'''
SNAKE_ALPHA  = 0.1    # era 0.015 → más rígido, evita que colapse
SNAKE_BETA   = 1.0    # era 10    → menos suave, el borde se adapta mejor
SNAKE_GAMMA  = 0.01   # era 0.001 → paso más grande, converge más rápido
SNAKE_ITERS  = 2500   # igual

#Me piden reducir de 256 a 32 0 64 niveles antes del GLCM
NIVELES_GLCM=32

#GLCM  distancias y angulos a calcular
GLCM_DISTANCIAS=[1,2]
GLCM_ANGULOS = [95,50,20,5]

# Nuevos: factores de calidad JPEG a comparar
CALIDADES_JPEG = [95, 50, 20, 5]

# Máscara a usar como ROI principal
# Usamos apertura (Otsu + morfología) porque es la más limpia
MASCARA_ROI = 'apertura'   # opciones: 'otsu', 'kmeans', 'snake', 'watershed', 'apertura'

# Estilo de plots
plt.rcParams['figure.dpi']     = 110
plt.rcParams['axes.titlesize'] = 11

#monto el drive y regenero variables
drive.mount('/content/drive')
#Parametros de morfologia
MORPH_RADIUS=5 #radio del elemento estructurante

# --- Carga y preprocesamiento ---
img_bgr   = cv2.imread(IMG_PATH)
img_rgb   = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
gray      = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)
gray_smooth = gaussian(gray, sigma=2)

# --- Otsu ---
umbral_otsu  = threshold_otsu(gray)
mascara_otsu = gray < umbral_otsu

# --- K-means ---
pixeles  = img_rgb.reshape(-1, 3).astype(np.float32)
criterio = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 100, 0.2)
_, etiquetas, centros = cv2.kmeans(pixeles, K_CLUSTERS, None, criterio, 10, cv2.KMEANS_RANDOM_CENTERS)
mapa_clusters  = etiquetas.reshape(img_rgb.shape[:2])
idx_oscuro     = np.argmin(centros.sum(axis=1))
mascara_kmeans = (mapa_clusters == idx_oscuro)

# --- Snake ---
_, binaria_ref = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
contornos_ref, _ = cv2.findContours(binaria_ref, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
contorno_mas_grande = max(contornos_ref, key=cv2.contourArea)
momentos = cv2.moments(contorno_mas_grande)
cx = int(momentos['m10'] / momentos['m00'])
cy = int(momentos['m01'] / momentos['m00'])
area_ref = cv2.contourArea(contorno_mas_grande)
radio = int(np.sqrt(area_ref / np.pi) * 1.4)
gray_para_snake   = gaussian(gray, sigma=3)
s = np.linspace(0, 2 * np.pi, 400)
contorno_inicial  = np.array([cy + radio * np.sin(s), cx + radio * np.cos(s)]).T
snake = active_contour(gray_para_snake, contorno_inicial,
    alpha=SNAKE_ALPHA, beta=SNAKE_BETA, gamma=SNAKE_GAMMA,
    w_line=0.0, w_edge=1.0, max_num_iter=SNAKE_ITERS)
rr_p, cc_p = polygon(snake[:, 0], snake[:, 1], gray.shape)
mascara_snake = np.zeros(gray.shape, dtype=bool)
mascara_snake[rr_p, cc_p] = True

# --- Watershed ---
gray_suave = cv2.GaussianBlur(gray, (5, 5), 0)
_, binaria = cv2.threshold(gray_suave, 0, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
distancia  = ndimage.distance_transform_edt(binaria)
coords_picos = peak_local_max(distancia, footprint=np.ones((3, 3)), labels=binaria)
mascara_picos = np.zeros(distancia.shape, dtype=bool)
mascara_picos[tuple(coords_picos.T)] = True
marcadores, _ = ndimage.label(mascara_picos)
etiquetas_ws  = watershed(-distancia, marcadores, mask=binaria)
mascara_watershed = etiquetas_ws > 0

# --- Morfología ---
elemento  = disk(MORPH_RADIUS)
erosionada  = erosion(mascara_otsu, elemento)
dilatada    = dilation(mascara_otsu, elemento)
apertura    = opening(mascara_otsu, elemento)
cierre      = closing(mascara_otsu, elemento)
esqueleto   = skeletonize(mascara_otsu)

# Seleccionamos la máscara ROI según config
opciones_mascara = {
    'otsu':       mascara_otsu,
    'kmeans':     mascara_kmeans,
    'snake':      mascara_snake,
    'watershed':  mascara_watershed,
    'apertura':   apertura,
}
mascara_roi = opciones_mascara[MASCARA_ROI]

print(f'Variables regeneradas correctamente.')
print(f'ROI seleccionada: {MASCARA_ROI} — {mascara_roi.sum()} píxeles activos')

"""## Preparación del ROI

Tres pasos previos al análisis:
1. **Recorte del ROI:** aplicamos la máscara para quedarnos solo con la lesión
2. **Cuantización:** reducimos de 256 a 32 niveles de gris. Esto es necesario para el GLCM porque con 256 niveles la matriz sería 256×256 y muy dispersa — con 32 niveles queda más representativa
3. **Separación de canales R, G, B:** el análisis de texturas se hace por canal por separado
"""

# Preparacion del ROI

#primero aplico la mascara a la imagen; np.where: donde la mascara es true → píxel original, donde es False → 0 (negro)
roi_rgb = np.where(mascara_roi[:,:,np.newaxis], img_rgb,0)

#ahora debo cuantizar los niveles de gris
#divido a cada pixel por (256 /NIVELES_GLCM) y convertimos a entero
#Esto mapea [0-255] → [0-(NIVELES_GLCM-1)]
factor = 256 // NIVELES_GLCM
gray_cuantizado = (gray // factor).astype(np.uint8)

#Aplicamos la mascaara tambien a la version cuantizada
roi_gray_cuant = np.where(mascara_roi, gray_cuantizado,0)

# Separar canales R, G, B del ROI
canal_R = np.where(mascara_roi, img_rgb[:, :, 0], 0)
canal_G = np.where(mascara_roi, img_rgb[:, :, 1], 0)
canal_B = np.where(mascara_roi, img_rgb[:, :, 2], 0)

# Cuantizamos también cada canal para el GLCM por canal
canal_R_cuant = (canal_R // factor).astype(np.uint8)
canal_G_cuant = (canal_G // factor).astype(np.uint8)
canal_B_cuant = (canal_B // factor).astype(np.uint8)

# --- Visualización ---
fig, axes = plt.subplots(2, 4, figsize=(16, 8))

axes[0][0].imshow(img_rgb);                         axes[0][0].set_title('Original')
axes[0][1].imshow(roi_rgb);                         axes[0][1].set_title(f'ROI ({MASCARA_ROI})')
axes[0][2].imshow(gray, cmap='gray');               axes[0][2].set_title('Grises original (256 niv.)')
axes[0][3].imshow(roi_gray_cuant, cmap='gray');     axes[0][3].set_title(f'ROI cuantizada ({NIVELES_GLCM} niv.)')

axes[1][0].imshow(canal_R, cmap='Reds');            axes[1][0].set_title('Canal R')
axes[1][1].imshow(canal_G, cmap='Greens');          axes[1][1].set_title('Canal G')
axes[1][2].imshow(canal_B, cmap='Blues');           axes[1][2].set_title('Canal B')
axes[1][3].imshow(mascara_roi, cmap='gray');        axes[1][3].set_title('Máscara ROI')

for ax in axes.ravel():
    ax.axis('off')

plt.suptitle('Preparación del ROI', fontweight='bold')
plt.tight_layout()
plt.show()

"""Calculo métricas sobre la **forma** de la máscara binaria, no sobre los colores.
Estas métricas sirven para cuantificar si la lesión es regular, grande, redonda, etc.

- **Área:** cantidad de píxeles en la región
- **Perímetro:** largo del borde en píxeles
- **Centroide:** coordenada (fila, columna) del centro de masa
- **Circularidad:** qué tan parecida es la forma a un círculo perfecto. Vale 1 para un círculo, menos para formas irregulares. Fórmula: `4π·área / perímetro²`
- **Excentricidad:** qué tan alargada es la región (0 = círculo, 1 = línea)
"""

# === DESCRIPTORES MORFOMÉTRICOS ===

# regionprops trabaja sobre una imagen etiquetada (label)
# label() convierte la máscara bool en una imagen donde cada región tiene un número distinto
mascara_etiquetada = label(mascara_roi)
props = regionprops(mascara_etiquetada)
'''
regionprops no trabaja sobre una máscara booleana (True/False) directamente. Necesita una imagen donde cada región tenga un número único
que la identifique. label() hace exactamente eso: toma tu máscara y asigna 1 a la primera región conectada, 2 a la segunda, etc.
Por ejemplo, si tu máscara tiene la lesión principal y algunos puntitos sueltos que quedaron del Otsu, label() les asigna números
distintos. Después max(..., key=lambda r: r.area) se queda solo con la región más grande, que es la lesión real, descartando los puntitos.
'''

# Nos quedamos con la región más grande (la lesión principal)
region = max(props, key=lambda r: r.area)

# Extraemos las métricas
area        = region.area
perimetro   = region.perimeter
centroide   = region.centroid      # (fila, columna)
excentricidad = region.eccentricity

'''
Estos los calcula regionprops internamente, no tenés que hacer nada. Lo importante es entender qué significa cada uno:

area: simplemente cuántos píxeles tiene la región. Si la imagen es de 224×224 y area=974, la lesión ocupa 974 de los 50.176 píxeles totales.
perimeter: largo del borde en píxeles. Se calcula contando los píxeles de la región que tienen al menos un vecino fuera de ella.
centroid: devuelve (fila, columna) del centro de masa. Es el promedio ponderado de las posiciones de todos los píxeles de la región.
  Importante: devuelve (fila, columna) y no (x, y), por eso en el plot se usa centroide[1] para el eje horizontal y centroide[0]
  para el vertical — es un error muy común confundirlos.
eccentricity: usa la elipse equivalente de la región para calcular qué tan alargada es. Vale 0 para un círculo perfecto y se acerca a 1 cuanto más alargada es la forma.
'''

# Circularidad: 4π·área / perímetro² → 1 = círculo perfecto
circularidad = (4 * np.pi * area) / (perimetro ** 2) if perimetro > 0 else 0
'''
Esta sí la calculamos a mano porque regionprops no la trae directamente. La fórmula viene de geometría: para un círculo perfecto, área = π·r²
y perímetro = 2π·r, si sustituís obtenés que 4π·área/perímetro² vale exactamente 1. Para cualquier otra forma, el perímetro es proporcionalmente
mayor al área, entonces el resultado cae por debajo de 1. Una lesión muy irregular (como un melanoma avanzado) tendrá circularidad baja, un lunar
redondo tendrá circularidad cercana a 1.
'''

print('=== DESCRIPTORES MORFOMÉTRICOS ===')
print(f'  Área:          {area} píxeles')
print(f'  Perímetro:     {perimetro:.1f} píxeles')
print(f'  Centroide:     fila={centroide[0]:.1f}, col={centroide[1]:.1f}')
print(f'  Circularidad:  {circularidad:.3f}  (1=círculo perfecto)')
print(f'  Excentricidad: {excentricidad:.3f}  (0=círculo, 1=línea)')

# Visualización: máscara con centroide marcado
fig, ax = plt.subplots(1, 2, figsize=(10, 4))
ax[0].imshow(img_rgb)
ax[0].imshow(mascara_roi, cmap='Reds', alpha=0.4)
ax[0].plot(centroide[1], centroide[0], 'b+', ms=15, mew=3, label='Centroide')
ax[0].set_title('ROI con centroide')
ax[0].legend()
ax[0].axis('off')

# Histograma de la máscara para ver la distribución de intensidades en el ROI
pixeles_roi = gray[mascara_roi]    # solo los píxeles dentro de la máscara
ax[1].hist(pixeles_roi, bins=50, color='steelblue', edgecolor='white')
ax[1].set_title('Histograma de intensidades — ROI')
ax[1].set_xlabel('Intensidad')
ax[1].set_ylabel('Cantidad de píxeles')

plt.suptitle('Descriptores Morfométricos', fontweight='bold')
plt.tight_layout()
plt.show()

"""Calculamos sobre los **píxeles de la ROI** (no sobre toda la imagen).
Se llaman de "primer orden" porque no tienen en cuenta la relación espacial entre píxeles,
solo la distribución de sus valores.

- **Media:** intensidad promedio → qué tan oscura/clara es la lesión
- **Desvío estándar:** dispersión → contraste interno de la lesión
- **Entropía:** complejidad/desorden del histograma → una lesión heterogénea tiene más entropía
- **Skewness (asimetría):** si la distribución se inclina hacia tonos claros (positivo) u oscuros (negativo)

Lo calculamos para los 3 canales R, G, B y los comparamos.
"""

# === DESCRIPTORES DE PRIMER ORDEN ===

def descriptores_primer_orden(canal, mascara, nombre):
    '''
    Recibe un canal de imagen, la máscara ROI y un nombre para imprimir.
    Devuelve un diccionario con las métricas.

    Separamos esto en una función porque lo vamos a llamar 3 veces (R, G, B).
    '''
    pixeles = canal[mascara].astype(float)   # solo los píxeles dentro de la ROI

    '''
    Lo primero y más importante: canal[mascara] es indexación booleana de NumPy. Cuando usás una máscara booleana como
    índice, NumPy te devuelve solo los valores donde la máscara es True, en forma de array 1D. Es decir, pixeles no es una
    imagen 2D sino una lista plana de los valores de intensidad únicamente dentro de la lesión. Esto es clave porque si calculáramos
    la media sobre toda la imagen estaríamos incluyendo el fondo negro, lo que arruinaría todas las métricas.
    '''

    media   = np.mean(pixeles)
    desvio  = np.std(pixeles)
    '''
    Estos son simples. La media te dice la intensidad promedio de la lesión en ese canal — si es baja, la lesión es oscura.
    El desvío estándar te dice cuánto varían los píxeles respecto a esa media — un desvío alto significa que hay zonas muy claras y muy
    oscuras dentro de la lesión, lo que en dermatología puede ser señal de heterogeneidad del pigmento.
    '''
    asimetria = skew(pixeles)                # scipy.stats.skew
    '''
    Skewness mide si el histograma es simétrico o se "inclina" hacia algún lado. Si es positivo, hay más píxeles oscuros y una cola hacia los claros.
    Si es negativo, hay más píxeles claros y una cola hacia los oscuros. Para una lesión pigmentada esperarías asimetría negativa en el canal azul
    (porque el pigmento absorbe el azul) y positiva en el rojo.
    '''

    # Para entropía necesitamos la distribución de probabilidad (histograma normalizado)
    hist, _ = np.histogram(pixeles, bins=256, range=(0, 256), density=True)
    hist    = hist[hist > 0]                 # eliminamos ceros para evitar log(0)
    entropia = entropy(hist)                 # scipy.stats.entropy — usa base e por defecto

    '''
    La entropía requiere un poco más de explicación. Primero np.histogram construye el histograma de probabilidades
    (density=True normaliza para que sume 1). Después hist[hist > 0] elimina los ceros — esto es necesario porque entropy
    internamente calcula p·log(p) y log(0) es infinito, lo que daría error.
    La entropía en este contexto mide cuánta variedad hay en el histograma: si todos los píxeles del ROI tienen el mismo valor, la entropía es
    0 (máximo orden). Si los valores están distribuidos uniformemente entre 0 y 255, la entropía es máxima. En términos prácticos, una lesión con
    textura compleja y variaciones de color tiene entropía alta; una zona de piel homogénea tiene entropía baja.
    '''

    print(f'  Canal {nombre}:')
    print(f'    Media:     {media:.2f}')
    print(f'    Desvío:    {desvio:.2f}')
    print(f'    Entropía:  {entropia:.4f}')
    print(f'    Skewness:  {asimetria:.4f}')

    return {'media': media, 'desvio': desvio, 'entropia': entropia, 'skewness': asimetria}

print('=== DESCRIPTORES DE PRIMER ORDEN ===')
metricas_R = descriptores_primer_orden(img_rgb[:, :, 0], mascara_roi, 'R')
metricas_G = descriptores_primer_orden(img_rgb[:, :, 1], mascara_roi, 'G')
metricas_B = descriptores_primer_orden(img_rgb[:, :, 2], mascara_roi, 'B')

# --- Visualización comparativa ---
canales    = ['R', 'G', 'B']
colores    = ['red', 'green', 'blue']
todas      = [metricas_R, metricas_G, metricas_B]
metricas_nombres = ['media', 'desvio', 'entropia', 'skewness']

fig, axes = plt.subplots(1, 4, figsize=(16, 4))

for ax, metrica in zip(axes, metricas_nombres):
    valores = [m[metrica] for m in todas]
    ax.bar(canales, valores, color=colores, alpha=0.8, edgecolor='black')
    ax.set_title(metrica.capitalize())
    ax.set_ylabel('Valor')

plt.suptitle('Descriptores de Primer Orden por canal R/G/B', fontweight='bold')
plt.tight_layout()
plt.show()

# Histogramas por canal dentro de la ROI
fig, axes = plt.subplots(1, 3, figsize=(14, 4))
for ax, canal_idx, nombre, color in zip(axes, [0, 1, 2], canales, colores):
    pixeles = img_rgb[:, :, canal_idx][mascara_roi]
    ax.hist(pixeles, bins=50, color=color, alpha=0.8, edgecolor='white')
    ax.set_title(f'Canal {nombre} — ROI')
    ax.set_xlabel('Intensidad')
    ax.set_ylabel('Cantidad')

plt.suptitle('Histogramas por canal dentro de la ROI', fontweight='bold')
plt.tight_layout()
plt.show()

'''
La pregunta que se responde con esto es cuál canal aporta más información sobre la textura. En imágenes dermatoscópicas generalmente el canal azul tiene
el mayor contraste para lesiones melanocíticas (el melanoma absorbe fuertemente en longitudes de onda corta), lo que se traduce en mayor desvío estándar y
mayor entropía en ese canal.
'''

"""La **GLCM (Gray-Level Co-occurrence Matrix)** captura relaciones espaciales entre píxeles:
en vez de mirar cada píxel por separado, mira qué tan seguido aparece un par de valores
(intensidad_A, intensidad_B) a cierta distancia y en cierta dirección.

Se llaman de "segundo orden" porque tienen en cuenta la relación entre pares de píxeles.

De la GLCM extraemos 4 atributos:
- **Contraste:** diferencia entre píxeles vecinos → textura rugosa = contraste alto
- **Correlación:** qué tan predecibles son los píxeles a partir de sus vecinos
- **Energía (ASM):** uniformidad → textura homogénea = energía alta
- **Homogeneidad:** similitud entre píxeles cercanos
"""

# === DESCRIPTORES DE SEGUNDO ORDEN — GLCM ===

def calcular_glcm(canal_cuant, mascara, niveles, nombre):
    '''
    Calcula la GLCM y extrae sus atributos para un canal dado.
    Separo en función para no repetir para R, G, B.

    Mejora respecto a la versión anterior: recortamos al bounding box
    de la máscara antes de calcular la GLCM. Así evitamos que el fondo
    (valor 0) domine la matriz y tape los valores reales de la lesión.
    '''
    # --- Recorte al bounding box de la máscara ---
    # np.any(mascara, axis=1) → True en las filas que tienen al menos un píxel activo
    # np.any(mascara, axis=0) → True en las columnas que tienen al menos un píxel activo
    filas    = np.any(mascara, axis=1)
    columnas = np.any(mascara, axis=0)
    fila_min, fila_max = np.where(filas)[0][[0, -1]]
    col_min,  col_max  = np.where(columnas)[0][[0, -1]]

    canal_recortado   = canal_cuant[fila_min:fila_max+1, col_min:col_max+1]
    mascara_recortada = mascara[fila_min:fila_max+1, col_min:col_max+1]

    # Aplicamos la máscara: píxeles fuera del ROI quedan en 0
    canal_enmascarado = (canal_recortado * mascara_recortada).astype(np.uint8)

    # graycomatrix(imagen, distancias, angulos, niveles)
    # Devuelve la GLCM: matriz de (niveles x niveles x n_distancias x n_angulos)
    glcm = graycomatrix(
        canal_enmascarado,
        distances=GLCM_DISTANCIAS,
        angles=GLCM_ANGULOS,
        levels=niveles,
        symmetric=True,    # considera ambas direcciones (i→j y j→i)
        normed=True        # normaliza para obtener probabilidades
    )

    # graycoprops extrae atributos de la GLCM completa (incluye nivel 0)
    # Los atributos se calculan sobre la GLCM completa — es lo correcto
    # Solo el plot excluye el nivel 0 para que sea legible visualmente
    contraste    = graycoprops(glcm, 'contrast').mean()
    correlacion  = graycoprops(glcm, 'correlation').mean()
    energia      = graycoprops(glcm, 'energy').mean()
    homogeneidad = graycoprops(glcm, 'homogeneity').mean()

    print(f'  Canal {nombre}:')
    print(f'    Contraste:     {contraste:.4f}')
    print(f'    Correlación:   {correlacion:.4f}')
    print(f'    Energía:       {energia:.4f}')
    print(f'    Homogeneidad:  {homogeneidad:.4f}')

    return {
        'contraste': contraste, 'correlacion': correlacion,
        'energia': energia, 'homogeneidad': homogeneidad,
        'glcm': glcm
    }

print(f'=== GLCM ({NIVELES_GLCM} niveles) ===')
glcm_R = calcular_glcm(canal_R_cuant, mascara_roi, NIVELES_GLCM, 'R')
glcm_G = calcular_glcm(canal_G_cuant, mascara_roi, NIVELES_GLCM, 'G')
glcm_B = calcular_glcm(canal_B_cuant, mascara_roi, NIVELES_GLCM, 'B')

# --- Visualización de la GLCM excluyendo nivel 0 del plot ---
# [1:, 1:, 0, 0] → saltamos fila 0 y columna 0 para que no tape todo
fig, axes = plt.subplots(1, 3, figsize=(14, 4))
for ax, glcm_data, nombre in zip(axes, [glcm_R, glcm_G, glcm_B], ['R', 'G', 'B']):
    glcm_plot = glcm_data['glcm'][1:, 1:, 0, 0]
    ax.imshow(glcm_plot, cmap='hot')
    ax.set_title(f'GLCM canal {nombre} (dist=1, ang=0°)\n(nivel 0 excluido del plot)')
    ax.set_xlabel('Nivel de gris j')
    ax.set_ylabel('Nivel de gris i')

plt.suptitle('Matrices GLCM por canal (calor = co-ocurrencia más frecuente)', fontweight='bold')
plt.tight_layout()
plt.show()

# --- Comparación de atributos por canal ---
atributos = ['contraste', 'correlacion', 'energia', 'homogeneidad']
fig, axes = plt.subplots(1, 4, figsize=(16, 4))
for ax, attr in zip(axes, atributos):
    valores = [glcm_R[attr], glcm_G[attr], glcm_B[attr]]
    ax.bar(['R', 'G', 'B'], valores, color=['red', 'green', 'blue'], alpha=0.8, edgecolor='black')
    ax.set_title(attr.capitalize())
plt.suptitle('Atributos GLCM por canal', fontweight='bold')
plt.tight_layout()
plt.show()

'''
La GLCM debería mostrar una diagonal brillante concentrada en los niveles altos (la piel rosada tiene intensidades altas en R, medias en G y bajas en B).
Esa diagonal indica que los píxeles vecinos tienden a tener valores similares — textura homogénea, que tiene sentido para una lesión.
Sobre los números que ya tenés: el contraste del canal R (5.64) siendo mucho mayor que G (1.90) y B (2.34) tiene sentido — la lesión oscura
contrasta más en el canal rojo porque el rojo domina la piel sana y está ausente en la lesión pigmentada. Eso ya es un resultado válido para discutir en la guía
'''

"""# PARTE 2 — Compresión de Imágenes

Huffman es un algoritmo de compresión **sin pérdida** basado en frecuencias:
- Los símbolos más frecuentes reciben códigos más cortos
- Los símbolos raros reciben códigos más largos

Para una imagen, los "símbolos" son los valores de píxel (0-255).
Si el nivel 200 (rosa claro de la piel) aparece muchas veces, le asignamos pocos bits.

Trabajamos sobre la imagen completa en escala de grises.
"""

# === HUFFMAN ===

def construir_arbol_huffman(frecuencias):
    '''
    Construye el árbol de Huffman a partir de un diccionario {símbolo: frecuencia}.
    Usa una cola de prioridad (heap): siempre combinamos los dos nodos de menor frecuencia.
    '''
    # Cada elemento del heap: [frecuencia, símbolo_o_None, hijo_izq, hijo_der]
    heap = [[freq, [sym, '']] for sym, freq in frecuencias.items()]
    heapq.heapify(heap)
    '''
    Primero construimos una lista de nodos, uno por cada nivel de gris que aparece en la imagen. Cada nodo tiene esta forma:
    [frecuencia, [símbolo, código_acumulado]]
    Por ejemplo para el nivel 200 con frecuencia 1400:
    [1400, [200, '']]

    El código empieza vacío '' porque todavía no sabemos qué bits le tocan.
    heapq.heapify convierte la lista en un heap mínimo: una estructura donde siempre podés sacar el elemento de menor frecuencia en O(1).
    Es como una fila de prioridad donde el más "barato" (menos frecuente) sale primero.
    '''

    while len(heap) > 1:
        # Tomamos los dos nodos de menor frecuencia
        lo = heapq.heappop(heap)
        hi = heapq.heappop(heap)
        # Asignamos '0' al de menor frecuencia y '1' al de mayor
        for par in lo[1:]:
            par[1] = '0' + par[1]
        for par in hi[1:]:
            par[1] = '1' + par[1]
        # Los combinamos en un nuevo nodo con frecuencia sumada
        heapq.heappush(heap, [lo[0] + hi[0]] + lo[1:] + hi[1:])

    '''
    Este es el corazón del algoritmo. En cada iteración:

    Sacamos los dos nodos de menor frecuencia (lo y hi)
    Al de menor frecuencia (lo) le agregamos '0' adelante de su código
    Al otro (hi) le agregamos '1' adelante
    Los combinamos en un nuevo nodo cuya frecuencia es la suma de ambas, y lo volvemos a meter al heap

    Esto se repite hasta que queda un solo nodo — la raíz del árbol. Al final cada símbolo tiene acumulado su código completo de 0s y 1s.
    Un ejemplo con 4 niveles simplificado:
    Inicio:  [1, A]  [3, B]  [5, C]  [8, D]

    Paso 1: combinamos A(1) y B(3) → nuevo nodo AB(4)
            A queda con '0', B con '1'

    Paso 2: combinamos AB(4) y C(5) → nuevo nodo ABC(9)
            A queda con '00', B con '10', C con '1'

    Paso 3: combinamos ABC(9) y D(8) → raíz(17)
            A='000', B='100', C='10', D='1'
    Los más frecuentes (D, C) tienen códigos más cortos. Los raros (A) tienen códigos largos.
    '''

    return dict(sorted(heapq.heappop(heap)[1:], key=lambda x: x[0]))

def calcular_compresion_huffman(imagen_gray):
    '''
    Calcula los códigos Huffman y estima cuántos bits necesitaría la imagen comprimida.
    No genera el archivo binario (eso requeriría manejo de bits), pero calcula la reducción.
    '''
    # Contar frecuencia de cada nivel de intensidad
    pixeles_flat = imagen_gray.flatten()
    frecuencias  = Counter(pixeles_flat.tolist())
    '''
    flatten() convierte la imagen 2D de 224×224 en un array 1D de 50.176 valores.
    Counter cuenta cuántas veces aparece cada valor — devuelve algo como {200: 1400, 185: 1200, 50: 3, ...}.
    '''

    # Construir árbol y obtener códigos
    codigos = construir_arbol_huffman(frecuencias)
    '''
    Llamamos a la función anterior y obtenemos un diccionario como:
    {200: '10', 185: '110', 50: '0001101', ...}
    '''

    # Calcular bits totales con Huffman
    bits_huffman = sum(frecuencias[s] * len(codigos[s]) for s in frecuencias)

    # Bits originales: 8 bits por píxel (256 niveles)
    bits_original = len(pixeles_flat) * 8

    ratio = bits_huffman / bits_original
    return codigos, bits_original, bits_huffman, ratio
    '''
    frecuencias[s] → cuántas veces aparece el símbolo s
    len(codigos[s]) → cuántos bits tiene su código Huffman
    Multiplicamos ambos y sumamos para todos los símbolos → total de bits que necesitaría la imagen comprimida
    bits_original es simplemente n_pixeles × 8 porque sin compresión cada píxel usa 8 bits fijos
    ratio menor a 1 significa que Huffman usa menos bits que el original
    '''

codigos_huff, bits_orig, bits_huff, ratio_huff = calcular_compresion_huffman(gray)

print('=== COMPRESIÓN HUFFMAN ===')
print(f'  Bits originales (8 bpp):     {bits_orig:,}')
print(f'  Bits con Huffman (estimado): {bits_huff:,}')
print(f'  Ratio de compresión:         {ratio_huff:.3f}  ({(1-ratio_huff)*100:.1f}% de reducción)')
print(f'  Bits por píxel promedio:     {bits_huff/gray.size:.2f} bpp')
print()
print('Muestra de códigos (10 más frecuentes):')
freq_sorted = sorted(Counter(gray.flatten().tolist()).items(), key=lambda x: -x[1])[:10]
for sym, freq in freq_sorted:
    print(f'  Nivel {sym:3d} (freq={freq:5d}) → código: {codigos_huff[sym]} ({len(codigos_huff[sym])} bits)')

# Visualización: longitud de código vs frecuencia
frecuencias_arr = Counter(gray.flatten().tolist())
niveles  = sorted(codigos_huff.keys())
longitudes = [len(codigos_huff[n]) for n in niveles]
freqs_ord  = [frecuencias_arr[n] for n in niveles]

fig, axes = plt.subplots(1, 2, figsize=(14, 4))
axes[0].bar(niveles, longitudes, color='steelblue', width=1)
axes[0].set_title('Longitud del código Huffman por nivel de gris')
axes[0].set_xlabel('Nivel de gris')
axes[0].set_ylabel('Bits')

axes[1].bar(niveles, freqs_ord, color='orange', width=1)
axes[1].set_title('Frecuencia de cada nivel de gris')
axes[1].set_xlabel('Nivel de gris')
axes[1].set_ylabel('Frecuencia')

plt.suptitle('Huffman — códigos y frecuencias', fontweight='bold')
plt.tight_layout()
plt.show()

"""RLE es el algoritmo de compresión **sin pérdida** más simple:
en vez de guardar cada píxel individualmente, guarda **pares (valor, cantidad)**.

Ejemplo: `[255, 255, 255, 100, 100]` → `[(255, 3), (100, 2)]`

Funciona bien cuando hay grandes zonas uniformes (fondos, máscaras binarias).
La guía pide aplicarlo en **dos direcciones**: horizontal (fila a fila) y vertical (columna a columna),
para comparar cuál da mejor compresión según la estructura de la imagen.
"""

# === RLE ===

def rle_codificar(secuencia):
    '''
    Aplica RLE a un array 1D.
    Devuelve lista de (valor, cantidad) y la cantidad total de pares.
    '''
    if len(secuencia) == 0:
        return [], 0

    codificado = []
    valor_actual = secuencia[0]
    contador     = 1

    for pixel in secuencia[1:]:
        if pixel == valor_actual:
            contador += 1
        else:
            codificado.append((valor_actual, contador))
            valor_actual = pixel
            contador     = 1

    codificado.append((valor_actual, contador))  # último grupo
    return codificado, len(codificado)

def rle_imagen(imagen, direccion='horizontal'):
    '''
    Aplica RLE a una imagen completa fila por fila (horizontal)
    o columna por columna (vertical).
    Devuelve el total de pares (menor = mejor compresión).
    '''
    total_pares = 0

    if direccion == 'horizontal':
        # Recorremos cada fila
        for fila in imagen:
            _, n_pares = rle_codificar(fila)
            total_pares += n_pares
    elif direccion == 'vertical':
        # Transponemos y recorremos cada "fila" (que son columnas originales)
        for columna in imagen.T:
            _, n_pares = rle_codificar(columna)
            total_pares += n_pares

    return total_pares

# RLE sobre la imagen en grises
pares_horiz = rle_imagen(gray, 'horizontal')
pares_vert  = rle_imagen(gray, 'vertical')

# Cada par (valor, cuenta) necesita: 8 bits para valor + suficientes bits para la cuenta
# Estimamos 8 bits para la cuenta también → 16 bits por par
bits_rle_horiz = pares_horiz * 16
bits_rle_vert  = pares_vert  * 16
bits_orig_total = gray.size * 8

print('=== COMPRESIÓN RLE ===')
print(f'  Píxeles totales:             {gray.size}')
print(f'  Bits originales (8 bpp):     {bits_orig_total:,}')
print()
print(f'  RLE Horizontal:')
print(f'    Pares generados:           {pares_horiz:,}')
print(f'    Bits estimados:            {bits_rle_horiz:,}')
print(f'    Ratio:                     {bits_rle_horiz/bits_orig_total:.3f} ({(1-bits_rle_horiz/bits_orig_total)*100:.1f}% reducción)')
print()
print(f'  RLE Vertical:')
print(f'    Pares generados:           {pares_vert:,}')
print(f'    Bits estimados:            {bits_rle_vert:,}')
print(f'    Ratio:                     {bits_rle_vert/bits_orig_total:.3f} ({(1-bits_rle_vert/bits_orig_total)*100:.1f}% reducción)')

# Visualización comparativa
metodos = ['Original\n(8 bpp)', f'RLE\nHorizontal', f'RLE\nVertical']
bits    = [bits_orig_total, bits_rle_horiz, bits_rle_vert]

fig, ax = plt.subplots(figsize=(7, 4))
bars = ax.bar(metodos, bits, color=['gray', 'steelblue', 'darkorange'], edgecolor='black', alpha=0.85)
ax.set_title('RLE — comparación horizontal vs vertical')
ax.set_ylabel('Bits estimados')
for bar, val in zip(bars, bits):
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() * 1.01,
            f'{val:,}', ha='center', va='bottom', fontsize=9)
plt.tight_layout()
plt.show()

"""JPEG es un algoritmo de compresión **con pérdida**: sacrifica calidad visual para reducir tamaño.
El factor de calidad va de 1 (máxima compresión, mínima calidad) a 95 (mínima compresión, máxima calidad).

JPEG usa la **transformada DCT** por bloques de 8×8 píxeles: convierte la imagen al dominio
de frecuencias y descarta las frecuencias altas (detalles finos) que el ojo humano percibe menos.

Los **artefactos de bloque** aparecen cuando la calidad es muy baja: se ven cuadrículas de 8×8 píxeles.
"""

# === JPEG ===

def comprimir_jpeg(imagen_rgb, calidad):
    '''
    Comprime una imagen RGB con JPEG a la calidad dada.
    Usa un buffer en memoria (io.BytesIO) para no guardar archivos.
    Devuelve la imagen descomprimida (para visualizar) y el tamaño en bytes.
    '''
    img_pil = Image.fromarray(imagen_rgb)

    # Guardar en memoria como JPEG
    buffer = io.BytesIO()
    img_pil.save(buffer, format='JPEG', quality=calidad)
    tamanio_bytes = buffer.tell()   # cuántos bytes ocupa el JPEG

    # Reabrir para ver cómo quedó después de la compresión
    buffer.seek(0)
    img_descomp = np.array(Image.open(buffer))

    return img_descomp, tamanio_bytes

# Tamaño original (sin compresión)
tamanio_original = img_rgb.nbytes

resultados_jpeg = []
for calidad in CALIDADES_JPEG:
    img_comp, size_bytes = comprimir_jpeg(img_rgb, calidad)
    ratio = size_bytes / tamanio_original
    resultados_jpeg.append({
        'calidad':  calidad,
        'imagen':   img_comp,
        'bytes':    size_bytes,
        'ratio':    ratio,
    })

# --- Visualización: imágenes a distintas calidades ---
fig, axes = plt.subplots(1, len(CALIDADES_JPEG) + 1, figsize=(20, 4))

axes[0].imshow(img_rgb)
axes[0].set_title(f'Original\n{tamanio_original:,} bytes')
axes[0].axis('off')

for ax, res in zip(axes[1:], resultados_jpeg):
    ax.imshow(res['imagen'])
    ax.set_title(f'JPEG Q={res["calidad"]}\n{res["bytes"]:,} bytes\n({res["ratio"]*100:.1f}% del original)')
    ax.axis('off')

plt.suptitle('Compresión JPEG — distintos factores de calidad', fontweight='bold')
plt.tight_layout()
plt.show()

# --- Gráfico de tamaño vs calidad ---
calidades_plot = [r['calidad']  for r in resultados_jpeg]
bytes_plot     = [r['bytes']    for r in resultados_jpeg]
ratios_plot    = [r['ratio']*100 for r in resultados_jpeg]

fig, axes = plt.subplots(1, 2, figsize=(12, 4))
axes[0].plot(calidades_plot, bytes_plot, 'o-', color='steelblue')
axes[0].axhline(tamanio_original, color='red', linestyle='--', label='Original')
axes[0].set_title('Tamaño vs calidad JPEG')
axes[0].set_xlabel('Factor de calidad')
axes[0].set_ylabel('Bytes')
axes[0].legend()

axes[1].plot(calidades_plot, ratios_plot, 'o-', color='darkorange')
axes[1].set_title('% del tamaño original vs calidad')
axes[1].set_xlabel('Factor de calidad')
axes[1].set_ylabel('% del original')
axes[1].axhline(100, color='red', linestyle='--', label='Original (100%)')
axes[1].legend()

plt.suptitle('Relación tamaño-calidad JPEG', fontweight='bold')
plt.tight_layout()
plt.show()

print('=== RESUMEN JPEG ===')
print(f'  Original: {tamanio_original:,} bytes')
for r in resultados_jpeg:
    print(f'  Q={r["calidad"]:2d}: {r["bytes"]:,} bytes ({r["ratio"]*100:.1f}% del original, reducción {(1-r["ratio"])*100:.1f}%)')

# === COMPARACIÓN FINAL ===

bits_jpeg_alta = resultados_jpeg[0]['bytes'] * 8   # calidad más alta de la lista
bits_jpeg_baja = resultados_jpeg[-1]['bytes'] * 8  # calidad más baja de la lista

metodos = [
    'Original\n(8 bpp)',
    'Huffman',
    'RLE\nHorizontal',
    'RLE\nVertical',
    f'JPEG Q={CALIDADES_JPEG[0]}\n(alta calidad)',
    f'JPEG Q={CALIDADES_JPEG[-1]}\n(baja calidad)',
]
bits_todos = [
    bits_orig_total,
    bits_huff,
    bits_rle_horiz,
    bits_rle_vert,
    bits_jpeg_alta,
    bits_jpeg_baja,
]
colores_barra = ['gray', 'steelblue', 'darkorange', 'peru', 'mediumseagreen', 'tomato']

fig, ax = plt.subplots(figsize=(14, 5))
bars = ax.bar(metodos, bits_todos, color=colores_barra, edgecolor='black', alpha=0.85)
ax.set_title('Comparación de algoritmos de compresión', fontweight='bold', fontsize=13)
ax.set_ylabel('Bits totales (estimado)')
for bar, val in zip(bars, bits_todos):
    ratio = val / bits_orig_total
    ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() * 1.01,
            f'{ratio:.2f}x', ha='center', va='bottom', fontsize=9, fontweight='bold')

plt.tight_layout()
plt.show()

print('=== TABLA COMPARATIVA ===')
print(f'{"Método":<30} {"Bits":>15} {"Ratio":>8} {"Reducción":>10} {"Con pérdida":>12}')
print('-' * 80)
datos = [
    ('Original (8 bpp)',         bits_orig_total,  False),
    ('Huffman',                  bits_huff,         False),
    ('RLE Horizontal',           bits_rle_horiz,    False),
    ('RLE Vertical',             bits_rle_vert,     False),
    (f'JPEG Q={CALIDADES_JPEG[0]}',  bits_jpeg_alta,    True),
    (f'JPEG Q={CALIDADES_JPEG[-1]}', bits_jpeg_baja,    True),
]
for nombre, bits, perdida in datos:
    ratio    = bits / bits_orig_total
    reduccion = (1 - ratio) * 100
    perdida_str = 'Sí' if perdida else 'No'
    print(f'{nombre:<30} {bits:>15,} {ratio:>8.3f} {reduccion:>9.1f}%  {perdida_str:>12}')